//var name=require('./name');
import name from './name';
import math from './src/js/math';
import array from './src/js/array';
//document.getElementById('app').textContent="aaa  "+math.randomStr();
//require('./style.css');
//import './style.css';
//console.log(name);
var arr=['3','5','6','3',"4"];
var arr1=['3'];
alert(array.unique(arr));
